// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nhf-portal/NhfPortal.tsx": () => import("../components/mockups/nhf-portal/NhfPortal.tsx")
};
